version: '3.8'
services:
  backend:
    image: backend
    build:
      context: ./server
    ports:
      - 5000:3000
    restart: unless-stopped
    volumes:
      - ./server/:/app/
      - /app/node_modules

  frontend:
    build: ./client
    container_name: 'frontend'
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/app
      - '/app/node_modules'
