version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./backup/:/backup/
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5438:5432'

  backend:
    image: backend
    build:
      context: ./server
    container_name: 'backend'
    ports:
      - 5000:3000
    entrypoint: /bin/sh
    command: -c "npx prisma migrate dev && npm run start"
    restart: unless-stopped
    volumes:
      - ./server/:/app/
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: 'frontend'
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/app
      - '/app/node_modules'

volumes:
  pgdata:
